type: rpm-ostree
repos:
install:
remove:
    - firefox
    - firefox-langpacks
    - kf5-akonadi-server-mysql
    - kf5-akonadi-server
    - kmousetool
    - okular
    - krfb-libs
    - krfb
    - kmag
    - mariadb-backup
    - mariadb-cracklib-password-check
    - mariadb-common
    - mariadb-server-utils
    - mariadb-server
    - mariadb-errmsg
    - mariadb-gssapi-server
    - mariadb
    - filelight
    - gwenview
    - gwenview-libs
    - mariadb-connector-c
    - mariadb-connector-c-config
    - perl-DBD-MariaDB
    - qt5-qtbase-mysql