type: bling # configure what to pull in from ublue-os/bling
  install:
    - fonts # selection of common good free fonts
    -
      # - ublue-update # https://github.com/ublue-os/ublue-update
    # - dconf-update-service # a service unit that updates the dconf db on boot
    # - devpod # https://devpod.sh/ as an rpm