# image will be published to ghcr.io/<user>/<name>
name: ublue-kinoite-light
# description will be included in the image's metadata
description: Ublue kinoite minimal

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  # configuration you wish to end up in /etc/ on the booted system should be 
                  # added into /usr/etc/ as that is the proper "distro" config directory on ostree
                  # read more in the files module's README
  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
    #  will be installed and set up
    custom-flatpaks: # this section is optional
    # - Celluloid: io.github.celluloid_player.Celluloid
    # - Krita: org.kde.krita

  - type: rpm-ostree
    install:
      - steam-devices
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - kf5-akonadi-server-mysql
      - kf5-akonadi-server
      - kmousetool
      - okular
      - krfb-libs
      - krfb
      - kmag
      - mariadb-backup
      - mariadb-cracklib-password-check
      - mariadb-common
      - mariadb-server-utils
      - mariadb-server
      - mariadb-errmsg
      - mariadb-gssapi-server
      - mariadb
      - filelight
      - gwenview
      - gwenview-libs
      - mariadb-connector-c
      - mariadb-connector-c-config
      - perl-DBD-MariaDB
      - qt5-qtbase-mysql

  - type: systemd
    user:
      enabled:
        - podman.service
        - podman-auto-update.timer

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      - kinoite.sh
      - main-post-install.sh
