# image will be published to ghcr.io/<user>/<name>
name: ublue-kinoite-with-libvirt-bore-eevdf
# description will be included in the image's metadata
description: Ublue kinoite with libvirt qemu kvm virtualization

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:

  - from-file: recipe-kinoite-light-libvirt.yml

  - type: rpm-ostree
    install:
      - uksmd-rawhide

  - type: systemd
    system:
      enabled:
        - uksmd.service