# image will be published to ghcr.io/<user>/<name>
name: ublue-kinoite-light-bore-eevdf
# description will be included in the image's metadata
description: Ublue kinoite minimal with cachyos bore eevdf kernel

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:

  - type: files
    files:
      - usr: /usr # copy static configurations
          # configuration you wish to end up in /etc/ on the booted system should be
          # added into /usr/etc/ as that is the proper "distro" config directory on ostree
        # read more in the files module's README

  - from-file: kinoite-light-yafti.yml

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-addons-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - kernel-cachyos-bore-eevdf
      - libcap-ng-devel
      - procps-ng-devel
      - uksmd
    remove:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra
      - firefox
      - firefox-langpacks
      - kf5-akonadi-server-mysql
      - kf5-akonadi-server
      - kmousetool
      - okular
      - krfb-libs
      - krfb
      - kmag
      - mariadb-backup
      - mariadb-cracklib-password-check
      - mariadb-common
      - mariadb-server-utils
      - mariadb-server
      - mariadb-errmsg
      - mariadb-gssapi-server
      - mariadb
      - filelight
      - gwenview
      - gwenview-libs
      - mariadb-connector-c
      - mariadb-connector-c-config
      - perl-DBD-MariaDB
      - qt5-qtbase-mysql

  - type: systemd
    system:
      enable:
        - uksmd.service
      disable:
    user:
      disable:
      enable:
        - podman.service
        - podman-auto-update.timer

  - from-file: kinoite-light-script.yml