# image will be published to ghcr.io/<user>/<name>
name: ucore-zfs-rpm-podman-hci-vgpu
# description will be included in the image's metadata
description: Ucore minimal with zfs, libvirt and nvidida vgpu unlocked

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore-hci
image-version: stable-zfs # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:

  - from-file: recipe-ucore-zfs-light.yml

  - type: script
    scripts:
      - vgpu.sh