# image will be published to ghcr.io/<user>/<name>
name: ublue-kinoite-light
# description will be included in the image's metadata
description: Ublue kinoite minimal

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:

  - type: files
    files:
      - usr: /usr # copy static configurations
                  # configuration you wish to end up in /etc/ on the booted system should be 
                  # added into /usr/etc/ as that is the proper "distro" config directory on ostree
                  # read more in the files module's README

  - from-file: kinoite-light-packages.yml

  - from-file: kinoite-light-yafti.yml

  - from-file: kinoite-light-systemd.yml

  - from-file: kinoite-light-script.yml