# image will be published to ghcr.io/<user>/<name>
name: ublue-kinoite-with-libvirt-bore-eevdf
# description will be included in the image's metadata
description: Ublue kinoite with libvirt qemu kvm virtualization

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
          # configuration you wish to end up in /etc/ on the booted system should be
          # added into /usr/etc/ as that is the proper "distro" config directory on ostree
        # read more in the files module's README

  - from-file: kinoite-light-packages.yml
  - from-file: kinoite-light-yafti.yml
  - from-file: kinoite-light-systemd.yml
  - from-file: kinoite-light-script.yml

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-addons-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - kernel-cachyos-bore-eevdf
      - libcap-ng-devel
      - procps-ng-devel
      - uksmd
      - qemu-kvm
      - libvirt
      - virt-manager
      - kate
      - podman
      - distrobox
      - htop
      - hwloc-gui
    remove:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra

  - type: systemd
    system:
      enabled:
        - uksmd.service
        - libvirtd.service