type: rpm-ostree
remove:
  - moby-engine
  - toolbox
  - distrobox
  - lzop
  - mbuffer
  - perl-Capture-Tiny
  - perl-Config-IniFiles
  - podman-compose
  - pv
  - qemu-guest-agent
  - tailscale
  - tmux
  - vim-enhanced
  - wireguard-tools
  - xdg-dbus-proxy
  - xdg-user-dirs