name: sync-fork
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: sync template
        run: gh repo sync vietchinh/ulightblue -b template
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
      - name: sync master
        run: gh repo sync vietchinh/ulightblue -b master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
      - name: git checkout
        uses: actions/checkout@v4
        with:
          ref: template
      - name: Commit & Push changes to master
        uses: benkaiser/rebase-commit-push@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          rebase: true
          message: "chore: auto rebase ${date}"
          branch: "master"
          author_email: "1348151+vietchinh@users.noreply.github.com"
          author_name: "vietchinh"