name: sync-fork
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: sync template
        run: gh repo sync vietchinh/ulightblue -b template
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: template
      - name: sync main
        run: gh repo sync vietchinh/ulightblue -b main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: template
      - name: sync live
        run: gh repo sync vietchinh/ulightblue -b live
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: template